// tb_ascon_permutation.sv
// ---------------------------------------------------------------------------
// Testbench for ascon_permutation (chains ascon_round 12 or 6 times).
// Golden vectors generated from model/ascon_ref.cpp's permutation() function.
// ---------------------------------------------------------------------------

module tb_ascon_permutation;

    logic clk, rst_n, start, busy, done;
    logic [3:0] num_rounds;
    logic [63:0] x0_in, x1_in, x2_in, x3_in, x4_in;
    logic [63:0] x0_out, x1_out, x2_out, x3_out, x4_out;
    int errors;

    ascon_permutation dut (
        .clk(clk), .rst_n(rst_n), .start(start), .num_rounds(num_rounds),
        .x0_in(x0_in), .x1_in(x1_in), .x2_in(x2_in), .x3_in(x3_in), .x4_in(x4_in),
        .busy(busy), .done(done),
        .x0_out(x0_out), .x1_out(x1_out), .x2_out(x2_out), .x3_out(x3_out), .x4_out(x4_out)
    );

    initial clk = 0;
    always #5 clk = ~clk;

    task automatic check_perm_vector(
        input logic [3:0] n,
        input logic [63:0] i0, i1, i2, i3, i4,
        input logic [63:0] e0, e1, e2, e3, e4,
        input string label
    );
        num_rounds = n;
        x0_in = i0; x1_in = i1; x2_in = i2; x3_in = i3; x4_in = i4;
        start = 1;
        @(posedge clk); #1;
        start = 0;

        for (int cyc = 0; cyc < 1200 && !done; cyc++) begin
            @(posedge clk); #1;
        end

        if (!done) begin
            errors++;
            $display("FAIL [%s]: never asserted done", label);
        end else if (x0_out !== e0 || x1_out !== e1 || x2_out !== e2 ||
                     x3_out !== e3 || x4_out !== e4) begin
            errors++;
            $display("FAIL [%s]", label);
            $display("  got : %016h %016h %016h %016h %016h",
                      x0_out, x1_out, x2_out, x3_out, x4_out);
            $display("  want: %016h %016h %016h %016h %016h", e0, e1, e2, e3, e4);
        end else begin
            $display("PASS [%s]", label);
        end

        @(posedge clk); #1; // let FINISH clear back to IDLE, settled
    endtask

    initial begin
        errors = 0;
        rst_n = 0;
        start = 0;
        num_rounds = 0;
        x0_in = 0; x1_in = 0; x2_in = 0; x3_in = 0; x4_in = 0;

        repeat (2) @(posedge clk); #1;
        rst_n = 1;
        @(posedge clk); #1;

        // Vectors generated by model/ascon_ref.cpp (permutation function)

        check_perm_vector(4'd12,
            64'h0000000080400C06, 64'h0001020304050607, 64'h08090A0B0C0D0E0F, 64'h1011121314151617, 64'h18191A1B1C1D1E1F,
            64'h4F18916B090308AB, 64'h6C937F21A76CEC8A, 64'hBE76CE36EB58BC2E, 64'h8ECB7376F43A223E, 64'h1DBC80609B7C4CBF,
            "iv-like-p_a"
        );

        check_perm_vector(4'd6,
            64'h0000000080400C06, 64'h0001020304050607, 64'h08090A0B0C0D0E0F, 64'h1011121314151617, 64'h18191A1B1C1D1E1F,
            64'hC38FE36682130664, 64'h06AEAD7007BF21B8, 64'h35CD0001D0EC8D1F, 64'h83712C29F835F2F8, 64'hBE4C8E4BD41B0F94,
            "iv-like-p_b"
        );

        check_perm_vector(4'd12,
            64'h0000000000000000, 64'h0000000000000000, 64'h0000000000000000, 64'h0000000000000000, 64'h0000000000000000,
            64'h78EA7AE5CFEBB108, 64'h9B9BFB8513B560F7, 64'h6937F83E03D11A50, 64'h3FE53F36F2C1178C, 64'h045D648E4DEF12C9,
            "all-zero-p_a"
        );

        check_perm_vector(4'd12,
            64'hFFFFFFFFFFFFFFFF, 64'hFFFFFFFFFFFFFFFF, 64'hFFFFFFFFFFFFFFFF, 64'hFFFFFFFFFFFFFFFF, 64'hFFFFFFFFFFFFFFFF,
            64'hD41D05295E134833, 64'h1CAB2F56F80B9CF8, 64'h11D0A2227D75CEF3, 64'hFC9A13721D19D0B4, 64'h31CC91248B3CD722,
            "all-ones-p_a"
        );

        check_perm_vector(4'd12,
            64'h0123456789ABCDEF, 64'hFEDCBA9876543210, 64'h1111111111111111, 64'hAAAAAAAAAAAAAAAA, 64'h5555555555555555,
            64'h3C0D12E3B4BBD35F, 64'h9D0C165572242A60, 64'h27A00A3B22451B79, 64'hD3719F2754DE4D85, 64'h08D9BE83C3CC92AE,
            "mixed-pattern-1-p_a"
        );

        check_perm_vector(4'd6,
            64'h0000000000000000, 64'h0000000000000000, 64'h0000000000000000, 64'h0000000000000000, 64'h0000000000000000,
            64'h160C84F20FAAD4F1, 64'h21495B1B0AE33EEF, 64'hE0377D04E23A914B, 64'h2B23481598FFA8EA, 64'h649AF379BA83CD30,
            "all-zero-p_b"
        );

        check_perm_vector(4'd6,
            64'hFFFFFFFFFFFFFFFF, 64'hFFFFFFFFFFFFFFFF, 64'hFFFFFFFFFFFFFFFF, 64'hFFFFFFFFFFFFFFFF, 64'hFFFFFFFFFFFFFFFF,
            64'h907003131B28ECFB, 64'h1676B68AB79738F8, 64'hA42C876002E79CB7, 64'h13A87732E898243E, 64'h35C773698C6490DE,
            "all-ones-p_b"
        );

        check_perm_vector(4'd6,
            64'h0123456789ABCDEF, 64'hFEDCBA9876543210, 64'h1111111111111111, 64'hAAAAAAAAAAAAAAAA, 64'h5555555555555555,
            64'h9D127E6683D158D6, 64'h43EE5B0951E0F3A4, 64'h2BBA60CB2CB00B02, 64'h98056896B7FF3B93, 64'hDFF9410BBF09E487,
            "mixed-pattern-1-p_b"
        );

        if (errors == 0)
            $display("\n*** ALL PERMUTATION VECTORS MATCH THE C++ REFERENCE MODEL ***");
        else
            $display("\n*** %0d MISMATCH(ES) FOUND ***", errors);

        $finish;
    end

endmodule
