// tb_ascon_round.sv
// ---------------------------------------------------------------------------
// Testbench for ascon_round (add_rc -> serial S-box -> diffusion, chained).
// Golden vectors generated from model/ascon_ref.cpp's full_round() function,
// an independent reimplementation of the same three-stage chain.
//
// NOTE ON TIMING: per the lesson learned in tb_ascon_sbox_serial.sv, every
// @(posedge clk) that's followed by reading a DUT signal is followed by a
// small #1 settle delay, to avoid reading a signal before its non-blocking
// update has actually committed.
// ---------------------------------------------------------------------------

module tb_ascon_round;

    logic clk, rst_n, start, busy, done;
    logic [3:0] round;
    logic [63:0] x0_in, x1_in, x2_in, x3_in, x4_in;
    logic [63:0] x0_out, x1_out, x2_out, x3_out, x4_out;
    int errors;

    ascon_round dut (
        .clk(clk), .rst_n(rst_n), .start(start), .round(round),
        .x0_in(x0_in), .x1_in(x1_in), .x2_in(x2_in), .x3_in(x3_in), .x4_in(x4_in),
        .busy(busy), .done(done),
        .x0_out(x0_out), .x1_out(x1_out), .x2_out(x2_out), .x3_out(x3_out), .x4_out(x4_out)
    );

    initial clk = 0;
    always #5 clk = ~clk;

    task automatic check_round_vector(
        input logic [3:0] r,
        input logic [63:0] i0, i1, i2, i3, i4,
        input logic [63:0] e0, e1, e2, e3, e4,
        input string label
    );
        round = r;
        x0_in = i0; x1_in = i1; x2_in = i2; x3_in = i3; x4_in = i4;
        start = 1;
        @(posedge clk); #1;
        start = 0;

        for (int cyc = 0; cyc < 100 && !done; cyc++) begin
            @(posedge clk); #1;
        end

        if (!done) begin
            errors++;
            $display("FAIL [%s]: never asserted done", label);
        end else if (x0_out !== e0 || x1_out !== e1 || x2_out !== e2 ||
                     x3_out !== e3 || x4_out !== e4) begin
            errors++;
            $display("FAIL [%s]", label);
            $display("  got : %016h %016h %016h %016h %016h",
                      x0_out, x1_out, x2_out, x3_out, x4_out);
            $display("  want: %016h %016h %016h %016h %016h", e0, e1, e2, e3, e4);
        end else begin
            $display("PASS [%s]", label);
        end

        @(posedge clk); #1; // let FINISH clear back to IDLE, settled
    endtask

    initial begin
        errors = 0;
        rst_n = 0;
        start = 0;
        round = 0;
        x0_in = 0; x1_in = 0; x2_in = 0; x3_in = 0; x4_in = 0;

        repeat (2) @(posedge clk); #1;
        rst_n = 1;
        @(posedge clk); #1;

        // Vectors generated by model/ascon_ref.cpp (full_round function)

        check_round_vector(4'd0,
            64'h0000000080400C06, 64'h0001020304050607, 64'h08090A0B0C0D0E0F, 64'h1011121314151617, 64'h18191A1B1C1D1E1F,
            64'h7F1597E93E8FC4DD, 64'h0701980A646D5FED, 64'h3FFFFFFFFFFFFF74, 64'h3FFB0000806054D7, 64'h101C1C1E1F1C1812,
            "round-0-iv-like"
        );

        check_round_vector(4'd0,
            64'h0000000000000000, 64'h0000000000000000, 64'h0000000000000000, 64'h0000000000000000, 64'h0000000000000000,
            64'h001E0F00000000F0, 64'h00000001E0000770, 64'h3FFFFFFFFFFFFF74, 64'h3C780000000000F0, 64'h0000000000000000,
            "all-zero"
        );

        check_round_vector(4'd1,
            64'hFFFFFFFFFFFFFFFF, 64'hFFFFFFFFFFFFFFFF, 64'hFFFFFFFFFFFFFFFF, 64'hFFFFFFFFFFFFFFFF, 64'hFFFFFFFFFFFFFFFF,
            64'hFFFFFFFFFFFFFFFF, 64'h00000001C20007E9, 64'hFBFFFFFFFFFFFF6D, 64'hC7CF7FFFFFFFFF1E, 64'hFFFFFFFFFFFFFFFF,
            "all-ones"
        );

        check_round_vector(4'd2,
            64'h0123456789ABCDEF, 64'hFEDCBA9876543210, 64'h1111111111111111, 64'hAAAAAAAAAAAAAAAA, 64'h5555555555555555,
            64'h0894CC24088C80C6, 64'hE582F586B85F2A1B, 64'h02C11DB6A42FF3E0, 64'h752050FAAF27BEC6, 64'h10334433CDEE99EE,
            "mixed-pattern-1"
        );

        check_round_vector(4'd3,
            64'h8000000000000000, 64'h0000000000000001, 64'hDEADBEEFCAFEBABE, 64'h0F0F0F0F0F0F0F0F, 64'hF0F0F0F0F0F0F0F0,
            64'h3817ACF189E6B3C0, 64'hEBDB2979DA2B8D65, 64'hF63563D7241EA91F, 64'hE35B852951841F52, 64'hFDFFFFFFFF7FFFFE,
            "mixed-pattern-2"
        );

        check_round_vector(4'd4,
            64'h0102030405060708, 64'h1122334455667788, 64'h9988776655443322, 64'hA5A5A5A5A5A5A5A5, 64'h5A5A5A5A5A5A5A5A,
            64'h1413A630D84DFC19, 64'hA3148D46098C3F1D, 64'h573C2EC269D20EE0, 64'h52F8D519D54CB361, 64'hEFDD88AABBDD8823,
            "mixed-pattern-3"
        );

        if (errors == 0)
            $display("\n*** ALL FULL-ROUND VECTORS MATCH THE C++ REFERENCE MODEL ***");
        else
            $display("\n*** %0d MISMATCH(ES) FOUND ***", errors);

        $finish;
    end

endmodule
