// tb_ascon_ad_absorb.sv
// ---------------------------------------------------------------------------
// Testbench for ascon_ad_absorb. Drives the block_req/block_valid streaming
// handshake to feed in AD blocks, then checks the final state against
// golden vectors generated by model/ascon_ref.cpp's ad_absorb() function
// (which mirrors the same block/padding/domain-separator protocol).
// ---------------------------------------------------------------------------

module tb_ascon_ad_absorb;

    logic clk, rst_n, start, has_ad, busy, done;
    logic [63:0] x0_in, x1_in, x2_in, x3_in, x4_in;
    logic [63:0] x0_out, x1_out, x2_out, x3_out, x4_out;

    logic        block_req;
    logic [63:0] block_data;
    logic        block_is_last;
    logic [3:0]  block_bytes;
    logic        block_valid;

    int errors;

    // Local shared permutation instance, wired the same way ascon_top does it.
    logic        perm_start, perm_busy, perm_done;
    logic [3:0]  perm_num_rounds;
    logic [63:0] perm_x0_in, perm_x1_in, perm_x2_in, perm_x3_in, perm_x4_in;
    logic [63:0] perm_x0_out, perm_x1_out, perm_x2_out, perm_x3_out, perm_x4_out;

    ascon_permutation perm_inst (
        .clk(clk), .rst_n(rst_n), .start(perm_start), .num_rounds(perm_num_rounds),
        .x0_in(perm_x0_in), .x1_in(perm_x1_in), .x2_in(perm_x2_in), .x3_in(perm_x3_in), .x4_in(perm_x4_in),
        .busy(perm_busy), .done(perm_done),
        .x0_out(perm_x0_out), .x1_out(perm_x1_out), .x2_out(perm_x2_out), .x3_out(perm_x3_out), .x4_out(perm_x4_out)
    );

    ascon_ad_absorb dut (
        .clk(clk), .rst_n(rst_n), .start(start), .has_ad(has_ad),
        .x0_in(x0_in), .x1_in(x1_in), .x2_in(x2_in), .x3_in(x3_in), .x4_in(x4_in),
        .block_req(block_req), .block_data(block_data),
        .block_is_last(block_is_last), .block_bytes(block_bytes), .block_valid(block_valid),
        .perm_start(perm_start), .perm_num_rounds(perm_num_rounds),
        .perm_x0_in(perm_x0_in), .perm_x1_in(perm_x1_in), .perm_x2_in(perm_x2_in),
        .perm_x3_in(perm_x3_in), .perm_x4_in(perm_x4_in),
        .perm_busy(perm_busy), .perm_done(perm_done),
        .perm_x0_out(perm_x0_out), .perm_x1_out(perm_x1_out), .perm_x2_out(perm_x2_out),
        .perm_x3_out(perm_x3_out), .perm_x4_out(perm_x4_out),
        .busy(busy), .done(done),
        .x0_out(x0_out), .x1_out(x1_out), .x2_out(x2_out), .x3_out(x3_out), .x4_out(x4_out)
    );

    initial clk = 0;
    always #5 clk = ~clk;

    // Base post-init state used as the input for every AD test case
    localparam logic [63:0] BASE_X0 = 64'hD65B8E3B2D49609B;
    localparam logic [63:0] BASE_X1 = 64'h0B3B2873A9D6DB9A;
    localparam logic [63:0] BASE_X2 = 64'hE9CAAF1722BC7BA7;
    localparam logic [63:0] BASE_X3 = 64'h3C53800A09B3263F;
    localparam logic [63:0] BASE_X4 = 64'hBC87958B1207B034;

    // Feed one block: wait for block_req, then present data/is_last/bytes
    // for one cycle with block_valid asserted.
    task automatic feed_block(
        input logic [63:0] data,
        input logic        is_last,
        input logic [3:0]  bytes
    );
        int wait_cyc = 0;
        while (!block_req && wait_cyc < 500) begin
            @(posedge clk); #1;
            wait_cyc++;
        end
        if (!block_req) $display("WARNING: block_req never asserted, timed out waiting");
        block_data    = data;
        block_is_last = is_last;
        block_bytes   = bytes;
        block_valid   = 1;
        @(posedge clk); #1;
        block_valid   = 0;
    endtask

    task automatic wait_done(int max_cycles);
        for (int cyc = 0; cyc < max_cycles && !done; cyc++) begin
            @(posedge clk); #1;
        end
    endtask

    task automatic check_result(
        input logic [63:0] e0, e1, e2, e3, e4,
        input string label
    );
        if (!done) begin
            errors++;
            $display("FAIL [%s]: never asserted done", label);
        end else if (x0_out !== e0 || x1_out !== e1 || x2_out !== e2 ||
                     x3_out !== e3 || x4_out !== e4) begin
            errors++;
            $display("FAIL [%s]", label);
            $display("  got : %016h %016h %016h %016h %016h",
                      x0_out, x1_out, x2_out, x3_out, x4_out);
            $display("  want: %016h %016h %016h %016h %016h", e0, e1, e2, e3, e4);
        end else begin
            $display("PASS [%s]", label);
        end
        @(posedge clk); #1; // let FINISH clear back to IDLE, settled
    endtask

    initial begin
        errors = 0;
        rst_n = 0;
        start = 0; has_ad = 0;
        block_data = 0; block_is_last = 0; block_bytes = 0; block_valid = 0;
        x0_in = 0; x1_in = 0; x2_in = 0; x3_in = 0; x4_in = 0;

        repeat (2) @(posedge clk); #1;
        rst_n = 1;
        @(posedge clk); #1;

        // --- Case 1: has_ad = 0 (skip entirely) ---
        x0_in = BASE_X0; x1_in = BASE_X1; x2_in = BASE_X2; x3_in = BASE_X3; x4_in = BASE_X4;
        has_ad = 0;
        start = 1;
        @(posedge clk); #1;
        start = 0;
        wait_done(50);
        check_result(BASE_X0, BASE_X1, BASE_X2, BASE_X3, BASE_X4, "no-ad-skip");

        // --- Case 2: single 3-byte partial block ---
        x0_in = BASE_X0; x1_in = BASE_X1; x2_in = BASE_X2; x3_in = BASE_X3; x4_in = BASE_X4;
        has_ad = 1;
        start = 1;
        @(posedge clk); #1;
        start = 0;
        feed_block(64'h0102030000000000, 1'b1, 4'd3);
        wait_done(800);
        check_result(
            64'h0BB7DA48A9F6869A, 64'h584DB678AC4D1B07, 64'h3D5FB897517D85BC,
            64'h1C7A606B20964237, 64'h17C528BA07736373,
            "single-partial-block-3bytes"
        );

        // --- Case 3: exact-multiple -- one full block + pure-padding block ---
        x0_in = BASE_X0; x1_in = BASE_X1; x2_in = BASE_X2; x3_in = BASE_X3; x4_in = BASE_X4;
        has_ad = 1;
        start = 1;
        @(posedge clk); #1;
        start = 0;
        feed_block(64'h0001020304050607, 1'b0, 4'd0);
        feed_block(64'h0000000000000000, 1'b1, 4'd0);
        wait_done(1600);
        check_result(
            64'h2C72B0659CF1EFD7, 64'h4594A26E7BC0363D, 64'hEF0949E398E66861,
            64'hF0C38E4D38B28849, 64'h52934CD413F467A8,
            "exact-multiple-padding-block"
        );

        // --- Case 4: two full blocks + 5-byte partial final block ---
        x0_in = BASE_X0; x1_in = BASE_X1; x2_in = BASE_X2; x3_in = BASE_X3; x4_in = BASE_X4;
        has_ad = 1;
        start = 1;
        @(posedge clk); #1;
        start = 0;
        feed_block(64'h0001020304050607, 1'b0, 4'd0);
        feed_block(64'h08090A0B0C0D0E0F, 1'b0, 4'd0);
        feed_block(64'h1011121314000000, 1'b1, 4'd5);
        wait_done(2400);
        check_result(
            64'h00B439483B96AE1E, 64'h19947E7BF47E1156, 64'h2CAC210B2EF54E25,
            64'hA8502303B5A30DC9, 64'hE714749E1CE3A566,
            "two-full-plus-partial"
        );

        if (errors == 0)
            $display("\n*** ALL AD ABSORB VECTORS MATCH THE C++ REFERENCE MODEL ***");
        else
            $display("\n*** %0d MISMATCH(ES) FOUND ***", errors);

        $finish;
    end

endmodule
