// tb_ascon_init.sv
// ---------------------------------------------------------------------------
// Testbench for ascon_init (load IV/key/nonce -> p^a -> XOR key into x3/x4).
// Golden vectors generated from model/ascon_ref.cpp's init() function.
// Uses fixed placeholder key/nonce values for verification -- not real
// secrets, just fixed test patterns.
// ---------------------------------------------------------------------------

module tb_ascon_init;

    logic clk, rst_n, start, busy, done;
    logic [127:0] key, nonce;
    logic [63:0] x0_out, x1_out, x2_out, x3_out, x4_out;
    int errors;

    // Local shared permutation instance, wired the same way ascon_top does
    // it -- ascon_init no longer owns its own ascon_permutation internally.
    logic        perm_start, perm_busy, perm_done;
    logic [3:0]  perm_num_rounds;
    logic [63:0] perm_x0_in, perm_x1_in, perm_x2_in, perm_x3_in, perm_x4_in;
    logic [63:0] perm_x0_out, perm_x1_out, perm_x2_out, perm_x3_out, perm_x4_out;

    ascon_permutation perm_inst (
        .clk(clk), .rst_n(rst_n), .start(perm_start), .num_rounds(perm_num_rounds),
        .x0_in(perm_x0_in), .x1_in(perm_x1_in), .x2_in(perm_x2_in), .x3_in(perm_x3_in), .x4_in(perm_x4_in),
        .busy(perm_busy), .done(perm_done),
        .x0_out(perm_x0_out), .x1_out(perm_x1_out), .x2_out(perm_x2_out), .x3_out(perm_x3_out), .x4_out(perm_x4_out)
    );

    ascon_init dut (
        .clk(clk), .rst_n(rst_n), .start(start),
        .key(key), .nonce(nonce),
        .perm_start(perm_start), .perm_num_rounds(perm_num_rounds),
        .perm_x0_in(perm_x0_in), .perm_x1_in(perm_x1_in), .perm_x2_in(perm_x2_in),
        .perm_x3_in(perm_x3_in), .perm_x4_in(perm_x4_in),
        .perm_busy(perm_busy), .perm_done(perm_done),
        .perm_x0_out(perm_x0_out), .perm_x1_out(perm_x1_out), .perm_x2_out(perm_x2_out),
        .perm_x3_out(perm_x3_out), .perm_x4_out(perm_x4_out),
        .busy(busy), .done(done),
        .x0_out(x0_out), .x1_out(x1_out), .x2_out(x2_out), .x3_out(x3_out), .x4_out(x4_out)
    );

    initial clk = 0;
    always #5 clk = ~clk;

    task automatic check_init_vector(
        input logic [63:0] key_hi, key_lo, nonce_hi, nonce_lo,
        input logic [63:0] e0, e1, e2, e3, e4,
        input string label
    );
        key   = { key_hi, key_lo };
        nonce = { nonce_hi, nonce_lo };
        start = 1;
        @(posedge clk); #1;
        start = 0;

        for (int cyc = 0; cyc < 1200 && !done; cyc++) begin
            @(posedge clk); #1;
        end

        if (!done) begin
            errors++;
            $display("FAIL [%s]: never asserted done", label);
        end else if (x0_out !== e0 || x1_out !== e1 || x2_out !== e2 ||
                     x3_out !== e3 || x4_out !== e4) begin
            errors++;
            $display("FAIL [%s]", label);
            $display("  got : %016h %016h %016h %016h %016h",
                      x0_out, x1_out, x2_out, x3_out, x4_out);
            $display("  want: %016h %016h %016h %016h %016h", e0, e1, e2, e3, e4);
        end else begin
            $display("PASS [%s]", label);
        end

        @(posedge clk); #1; // let FINISH clear back to IDLE, settled
    endtask

    initial begin
        errors = 0;
        rst_n = 0;
        start = 0;
        key = 0; nonce = 0;

        repeat (2) @(posedge clk); #1;
        rst_n = 1;
        @(posedge clk); #1;

        // Vectors generated by model/ascon_ref.cpp (init function)

        check_init_vector(
            64'h0001020304050607, 64'h08090A0B0C0D0E0F, 64'h0102030405060708, 64'h090A0B0C0D0E0F00,
            64'hD65B8E3B2D49609B, 64'h0B3B2873A9D6DB9A, 64'hE9CAAF1722BC7BA7, 64'h3C53800A09B3263F, 64'hBC87958B1207B034,
            "placeholder-key-nonce-1"
        );

        check_init_vector(
            64'h0000000000000000, 64'h0000000000000000, 64'h0000000000000000, 64'h0000000000000000,
            64'hB8DFF46B0DB421F8, 64'hED0232A7C68DED74, 64'h138A46B172B225F9, 64'hFA8EAAAAC685D26A, 64'hF044217FBE57E755,
            "all-zero-key-nonce"
        );

        check_init_vector(
            64'hFFFFFFFFFFFFFFFF, 64'hFFFFFFFFFFFFFFFF, 64'hFFFFFFFFFFFFFFFF, 64'hFFFFFFFFFFFFFFFF,
            64'hA276B5B99D5FB093, 64'h96FD2BFA8A0E2071, 64'hCA565DD2C9D09C79, 64'hFA60F807B93C29A8, 64'h36F6482A46D0F290,
            "all-ones-key-nonce"
        );

        if (errors == 0)
            $display("\n*** ALL INIT VECTORS MATCH THE C++ REFERENCE MODEL ***");
        else
            $display("\n*** %0d MISMATCH(ES) FOUND ***", errors);

        $finish;
    end

endmodule
